use_frameworks!

platform :ios, '9.0'

target 'WalkthroughTutorial_Example' do
  pod 'WalkthroughTutorial', :path => '../'

  target 'WalkthroughTutorial_Tests' do
    inherit! :search_paths

    
  end
end
